config/routes.rb
Rails.application.routes.draw do

  # AR Validation Topics
  root 'rails_validations#index'
  get 'validation_helpers' => 'rails_validations#validation_helpers'
  get 'common_validation_options' => 'rails_validations#common_validation_options'
  get 'strict_validations' => 'rails_validations#strict_validations'
  get 'conditional_validations' => 'rails_validations#conditional_validations'
  get 'custom_validations' => 'rails_validations#custom_validations'
  get 'play_with_errors' => 'rails_validations#play_with_errors'
end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/coffee_cup.rb
class CoffeeCup < ActiveRecord::Base
end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rails_validations_controller.rb
class RailsValidationsController < ApplicationController
  def index
  end

  def validation_helpers
  end

  def common_validation_options
  end

  def strict_validations
  end

  def conditional_validations
  end

  def custom_validations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/rails_validations_helper.rb
module RailsValidationsHelper
  def test
  end
end

app/views/layouts/_header.html.erb
<div class="header indigo z-depth-1">
  <nav class="indigo z-depth-0">
    <div class="nav-wrapper">
      <a class="page-title">RailsTutorials</a>
      <ul id="dropdown1" class="dropdown-content">
        <li><a href="javascript:;">Active Record Validations</a></li>
        <li><a href="javascript:;">Active Record Callbacks</a></li>
      </ul>
      <ul class="right">
        <li><a class="active" href="javascript:;">Home</a></li>
        <li><a class="dropdown-button" href="#" data-activates="dropdown1">Tutorial Index</a></li>
        <li><a href="javascript:;">Contribute</a></li>
        <li><a href="javascript:;">Credits</a></li>
      </ul>
    </div>
  </nav>
</div>
<script>
  $(document).ready(function(){
    $(".dropdown-button").dropdown();
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "#{params[:controller].humanize} | #{params[:action].humanize}" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header'%>
    <%= render 'shared/progressbar'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
</body>
</html>

app/views/rails_validations/common_validation_options.html.erb
<div class="row section-div ">
  <div class="col s6 content_div">
    <h4>Common Validation Options</h4>
    <ol>
      <li>
        <h5 class="flow-text-header">:allow_nil</h5>
        <p class="flow-text">
          The :allow_nil option skips the validation when the value being
          validated is nil.
        </p>
        <pre class="brush: ruby">
          class Coffee < ApplicationRecord
            validates :size, inclusion: { in: %w(small medium large),
              message: "%{value} is not a valid size" }, allow_nil: true
          end
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">:allow_blank</h5>
        <p class="flow-text">The :allow_blank option is similar to the :allow_nil
          option. This option will let validation pass if the attribute's value is
          blank?, like nil or an empty string for example.</p>
        <pre class="brush: ruby">
          class Topic < ApplicationRecord
            validates :title, length: { is: 5 }, allow_blank: true
          end

          Topic.create(title: "").valid?  # => true
          Topic.create(title: nil).valid? # => true
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">:message</h5>
        <p class="flow-text">
          As you've already seen, the :message option lets you specify the message
           that will be added to the errors collection when validation fails.
         </p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            # Hard-coded message
            validates :name, presence: { message: "must be given please" }

            # Message with dynamic attribute value. %{value} will be replaced with
            # the actual value of the attribute. %{attribute} and %{model} also
            # available.
            validates :age, numericality: { message: "%{value} seems wrong" }

            # Proc
            validates :username,
              uniqueness: {
                # object = person object being validated
                # data = { model: "Person", attribute: "Username", value: <username> }
                message: ->(object, data) do
                  "Hey #{object.name}!, #{data[:value]} is taken already! Try again #{Time.zone.tomorrow}"
                end
              }
          end
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">:on</h5>
        <p class="flow-text">
          The :on option lets you specify when the validation should happen.
        </p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            # it will be possible to update email with a duplicated value
            validates :email, uniqueness: true, on: :create

            # it will be possible to create the record with a non-numerical age
            validates :age, numericality: true, on: :update

            # the default (validates on both create and update)
            validates :name, presence: true
          end
        </pre>
      </li>
    </ol>
  </div>
  <div class="col s6">
    <%= render "shared/interactive_console"%>
  </div>
</div>
<script>
  $(document).ready(function(){
    SyntaxHighlighter.all({
      'quick-code': false
    });
    $('#console').style('margin-top', "-485px", 'important')
    $(".content_div").mCustomScrollbar({
      theme:"rounded-dark"
    });
  })
</script>

app/views/rails_validations/conditional_validations.html.erb
<div class="row section-div ">
  <div class="col s6 content_div">
    <h4>Conditional Validation</h4>
    <ol>
      <li>
        <h5 class="flow-text-header">Using a Symbol with :if and :unless</h5>
        <p class="flow-text">
          You can associate the :if and :unless options with a symbol corresponding
          to the name of a method that will get called right before validation happens.
          This is the most commonly used option
        </p>
        <pre class="brush: ruby">
          class Order < ApplicationRecord
            validates :card_number, presence: true, if: :paid_with_card?

            def paid_with_card?
              payment_type == "card"
            end
          end
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">Using a String with :if and :unless</h5>
        <p class="flow-text">You can also use a string that will be evaluated using
          eval and needs to contain valid Ruby code. You should use this option only
          when the string represents a really short condition.</p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            validates :surname, presence: true, if: "name.nil?"
          end
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">Using a Proc with :if and :unless</h5>
        <p class="flow-text">
          it's possible to associate :if and :unless with a Proc object which
          will be called. Using a Proc object gives you the ability to write an
          inline condition instead of a separate method.
        </p>
        <pre class="brush: ruby">
          class Account < ApplicationRecord
            validates :password, confirmation: true,
              unless: Proc.new { |a| a.password.blank? }
          end
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">Grouping Conditional validations</h5>
        <p class="flow-text">
          Sometimes it is useful to have multiple validations use one condition.
           It can be easily achieved using with_options.
        </p>
        <pre class="brush: ruby">
          class User < ApplicationRecord
            with_options if: :is_admin? do |admin|
              admin.validates :password, length: { minimum: 10 }
              admin.validates :email, presence: true
            end
          end
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">Combining Validation Conditions</h5>
        <p class="flow-text">
          On the other hand, when multiple conditions define whether or not a
          validation should happen, an Array can be used. Moreover, you can
          apply both :if and :unless to the same validation.
        </p>
        <pre class="brush: ruby">
          class Computer < ApplicationRecord
            validates :mouse, presence: true,
                              if: ["market.retail?", :desktop?],
                              unless: Proc.new { |c| c.trackpad.present? }
          end
        </pre>
      </li>
    </ol>
  </div>
  <div class="col s6">
    <%= render "shared/interactive_console"%>
  </div>
</div>
<script>
  $(document).ready(function(){
    SyntaxHighlighter.all({
      'quick-code': false
    });
    $('#console').style('margin-top', "-485px", 'important')
    $(".content_div").mCustomScrollbar({
      theme:"rounded-dark"
    });
  })
</script>

app/views/rails_validations/custom_validations.html.erb
<div class="row section-div ">
  <div class="col s6 content_div">
    <h4>Custom Validations</h4>
    <ul>
      <li>
        <h5 class="flow-text-header">Custom Validators</h5>
        <p class="flow-text">
          Custom validators are classes that inherit from ActiveModel::Validator.
          These classes must implement the validate method which takes a record as an
          argument and performs the validation on it. The custom validator is called
          using the validates_with method.
        </p>
        <pre class="brush: ruby">
          class MyValidator < ActiveModel::Validator
            def validate(record)
              unless record.name.starts_with? 'X'
                record.errors[:name] << 'Need a name starting with X please!'
              end
            end
          end

          class Person
            include ActiveModel::Validations
            validates_with MyValidator
          end
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">Custom Methods</h5>
        <p class="flow-text">
          You can also create methods that verify the state
          of your models and add messages to the errors collection when they are invalid.
        </p>
        <pre class="brush: ruby">
          class Invoice < ApplicationRecord
            validate :expiration_date_cannot_be_in_the_past,
              :discount_cannot_be_greater_than_total_value

            def expiration_date_cannot_be_in_the_past
              if expiration_date.present? && expiration_date < Date.today
                errors.add(:expiration_date, "can't be in the past")
              end
            end

            def discount_cannot_be_greater_than_total_value
              if discount > total_value
                errors.add(:discount, "can't be greater than total value")
              end
            end
          end
        </pre>
      </li>
    </ul>
  </div>
  <div class="col s6">
    <%= render "shared/interactive_console"%>
  </div>
</div>
<script>
  $(document).ready(function(){
    SyntaxHighlighter.all({
      'quick-code': false
    });
    $('#console').style('margin-top', "-485px", 'important')
    $(".content_div").mCustomScrollbar({
      theme:"rounded-dark"
    });
  })
</script>

app/views/rails_validations/index.html.erb
<div class="row section-div ">
  <div class="col s6 content_div">
    <h4>Introduction</h4>
    <pre class="brush: ruby">
      class Person < ActiveRecord::Base
        validates :name, presence: true
      end

      Person.create(name: "John Doe").valid? # => true
      Person.create(name: nil).valid? # => false
    </pre>
    <p class="flow-text">
      As you can see, our validation lets us know that our Person is not valid without a name attribute.
    </p>
    <hr>

    <h5>Why Use Validations?</h5>
    <ul class="collapsible popout" data-collapsible="accordion">
      <li>
        <div class="collapsible-header">DB constraints or stored procedures make validation mechanisms DB-dependent</div>
        <div class="collapsible-body">
          <p class="flow-text">
            Database constraints and/or stored procedures make the validation mechanisms database-dependent and can make testing and maintenance more difficult. However, if your database is used by other applications, it may be a good idea to use some constraints at the database level. Additionally, database-level validations can safely handle some things (such as uniqueness in heavily-used tables) that can be difficult to implement otherwise.
          </p>
        </div>
      </li>
      <li>
        <div class="collapsible-header">Client-side validations can be useful but unreliable and can be bypassed</div>
        <div class="collapsible-body">
          <p class="flow-text">
            Client-side validations can be useful, but are generally unreliable if used alone. If they are implemented using JavaScript, they may be bypassed if JavaScript is turned off in the user's browser. However, if combined with other techniques, client-side validation can be a convenient way to provide users with immediate feedback as they use your site.
          </p>
        </div>
      </li>
      <li>
        <div class="collapsible-header">Controller-level validations can be tempting but try to keep it skiny</div>
        <div class="collapsible-body">
          <p class="flow-text">
            Controller-level validations can be tempting to use, but often become unwieldy and difficult to test and maintain. Whenever possible, it's a good idea to keep your controllers skinny, as it will make your application a pleasure to work with in the long run.
          </p>
        </div>
      </li>
    </ul>
    <hr>
    <h5>When Does Validation Happen?</h5>
    <p class="flow-text">
      Creating and saving a new record will send an SQL INSERT operation to the database. Updating an existing record will send an SQL UPDATE operation instead. Validations are typically run before these commands are sent to the database. If any validations fail, the object will be marked as invalid and Active Record will not perform the INSERT or UPDATE operation.
    </p>

    <p class="flow-text">
      The following methods trigger validations, and will save the object to the database only if the object is valid:
    </p>
    <ol class="flow-text">
      <li>create</li>
      <li>create!</li>
      <li>save</li>
      <li>save!</li>
      <li>update</li>
      <li>update!</li>
    </ol>
    <p class="flow-text">
      The bang versions (e.g. save!) raise an exception if the record is invalid. The non-bang versions don't, save and update return false, create just returns the object.
    </p>
    <h5>Skipping Validations</h5>
    <p class="flow-text">The following methods skip validations</p>
    <ol class="flow-text">
      <li>decrement!</li>
      <li>decrement_counter</li>
      <li>increment!</li>
      <li>increment_counter</li>
      <li>toggle!</li>
      <li>touch</li>
      <li>update_all</li>
      <li>update_attribute</li>
      <li>update_column</li>
      <li>update_columns</li>
      <li>update_counters</li>
    </ol>
    <blockquote class="flow-text">
      Note that save also has the ability to skip validations if passed validate:
      false as argument. This technique should be used with caution.
      <b>save(validate: false)</b>
    </blockquote>
    <hr>
    <p class="flow-text">
      To verify whether or not an object is valid, Rails uses the valid? method. You can also use this method on your own. valid? triggers your validations and returns true if no errors were found in the object, and false otherwise
    </p>
    <h5>valid? and invalid?</h5>
    <pre class="brush: ruby">
      class Person < ActiveRecord::Base
        validates :name, presence: true
      end

      Person.create(name: "John Doe").valid? # => true
      Person.create(name: nil).valid? # => false
    </pre>
    <p class="flow-text">invalid? is simply the inverse of valid?</p>
  </div>
  <div class="col s6">
    <%= render "shared/interactive_console"%>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    SyntaxHighlighter.all({
      'quick-code': false
    });
    $('.collapsible').collapsible({
      accordion : false // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    });
    $('#console').style('margin-top', "-485px", 'important')
    $(".content_div").mCustomScrollbar({
      theme:"rounded-dark"
    });

  })
</script>

app/views/rails_validations/play_with_errors.html.erb
<div class="row section-div ">
  <div class="col s6 content_div">
    <h4>Playing with Validation Errors</h4>
    <p class="flow-text">
      Rails provides a number of methods for working with the
      errors collection and inquiring about the validity of objects
     </p>
     <p class="flow-text">
       The following is a list of the most commonly used methods:
     </p>
    <ul>
      <li>
        <h5 class="flow-text-header">errors</h5>
        <p class="flow-text">
          Returns an instance of the class ActiveModel::Errors containing all errors
        </p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            validates :name, presence: true, length: { minimum: 3 }
          end

          person = Person.new
          person.valid? # => false
          person.errors.messages
           # => {:name=>["can't be blank", "is too short (minimum is 3 characters)"]}

          person = Person.new(name: "John Doe")
          person.valid? # => true
          person.errors.messages # => {}
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">errors[]</h5>
        <p class="flow-text">
          errors[] is used when you want to check the error messages for a
          specific attribute
        </p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            validates :name, presence: true, length: { minimum: 3 }
          end

          person = Person.new(name: "John Doe")
          person.valid? # => true
          person.errors[:name] # => []

          person = Person.new(name: "JD")
          person.valid? # => false
          person.errors[:name] # => ["is too short (minimum is 3 characters)"]

          person = Person.new
          person.valid? # => false
          person.errors[:name]
           # => ["can't be blank", "is too short (minimum is 3 characters)"]
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">errors.add</h5>
        <p class="flow-text">
          The add method lets you add an error message related to a particular
          attribute. It takes as arguments the attribute and the error message.
        </p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            def a_method_used_for_validation_purposes
              errors.add(:name, "cannot contain the characters !@#%*()_-+=")
            end
          end

          person = Person.create(name: "!@#")

          person.errors[:name]
           # => ["cannot contain the characters !@#%*()_-+="]

          person.errors.full_messages
           # => ["Name cannot contain the characters !@#%*()_-+="]
        </pre>
        <p class="flow-text">
          An equivalent to errors#add is to use << to append a message to the
          errors.messages array for an attribute
        </p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            def a_method_used_for_validation_purposes
              errors.messages[:name] << "cannot contain the characters !@#%*()_-+="
            end
          end

          person = Person.create(name: "!@#")

          person.errors[:name]
           # => ["cannot contain the characters !@#%*()_-+="]

          person.errors.to_a
           # => ["Name cannot contain the characters !@#%*()_-+="]
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">errors.details</h5>
        <p class="flow-text">
          You can specify a validator type to the returned error details hash
          using the errors.add method.
        </p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            def a_method_used_for_validation_purposes
              errors.add(:name, :invalid_characters)
            end
          end

          person = Person.create(name: "!@#")

          person.errors.details[:name]
          # => [{error: :invalid_characters}]
        </pre>
        <p class="flow-text">
          To improve the error details to contain the unallowed characters set
          for instance, you can pass additional keys to errors.add.
        </p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            def a_method_used_for_validation_purposes
              errors.add(:name, :invalid_characters, not_allowed: "!@#%*()_-+=")
            end
          end

          person = Person.create(name: "!@#")

          person.errors.details[:name]
          # => [{error: :invalid_characters, not_allowed: "!@#%*()_-+="}]
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">errors[:base]</h5>
        <p class="flow-text">
          You can add error messages that are related to the object's state as
          a whole, instead of being related to a specific attribute.
        </p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            def a_method_used_for_validation_purposes
              errors[:base] << "This person is invalid because ..."
            end
          end
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">errors.clear</h5>
        <p class="flow-text">
          The clear method is used when you intentionally want to clear all the
          messages in the errors collection.
        </p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            validates :name, presence: true, length: { minimum: 3 }
          end

          person = Person.new
          person.valid? # => false
          person.errors[:name]
           # => ["can't be blank", "is too short (minimum is 3 characters)"]

          person.errors.clear
          person.errors.empty? # => true

          person.save # => false

          person.errors[:name]
          # => ["can't be blank", "is too short (minimum is 3 characters)"]
        </pre>
      </li>
      <li>
        <h5 class="flow-text-header">errors.size</h5>
        <p class="flow-text">
          The size method returns the total number of error messages for the object.
        </p>
        <pre class="brush: ruby">
          class Person < ApplicationRecord
            validates :name, presence: true, length: { minimum: 3 }
          end

          person = Person.new
          person.valid? # => false
          person.errors.size # => 2

          person = Person.new(name: "Andrea", email: "andrea@example.com")
          person.valid? # => true
          person.errors.size # => 0
        </pre>
      </li>
    </ul>
    <hr>
    <p class="flow-text-header">
      Displaying Validation Errors in Views
    </p>
    <pre class="brush: ruby">
      <%% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
          <%% @article.errors.full_messages.each do |msg| %>
            <li><%%= msg %></li>
          <%% end %>
          </ul>
        </div>
      <%% end %>
    </pre>
  </div>
  <div class="col s6">
    <%= render "shared/interactive_console"%>
  </div>
</div>
<script>
  $(document).ready(function(){
    SyntaxHighlighter.all({
      'quick-code': false
    });
    $('#console').style('margin-top', "-485px", 'important')
    $(".content_div").mCustomScrollbar({
      theme:"rounded-dark"
    });
  })
</script>

app/views/rails_validations/strict_validations.html.erb
<div class="row section-div ">
  <div class="col s6 content_div">
    <h4>Strict Validation</h4>
    <p class="flow-text">You can also specify validations to be strict and raise ActiveModel::StrictValidationFailed when the object is invalid.</p>
    <pre class="brush: ruby">
      class Person < ApplicationRecord
        validates :name, presence: { strict: true }
      end

      Person.new.valid?  # => ActiveModel::StrictValidationFailed: Name can't be blank
    </pre>
    <p class="flow-text">There is also the ability to pass a custom exception to the :strict option.</p>
    <pre class="brush: ruby">
      class Person < ApplicationRecord
        validates :token, presence: true, uniqueness: true, strict: TokenGenerationException
      end

      Person.new.valid?  # => TokenGenerationException: Token can't be blank
    </pre>
  </div>
  <div class="col s6">
    <%= render "shared/interactive_console"%>
  </div>
</div>
<script>
  $(document).ready(function(){
    SyntaxHighlighter.all();
    $('#console').style('margin-top', "-485px", 'important')
    $(".content_div").mCustomScrollbar({
      theme:"rounded-dark"
    });
  })
</script>

app/views/shared/_interactive_console.html.erb
<div class="console-font"><b>Interactive Rails console Ready!!</b></div>
<%= console %>
<script>
  $(document).ready(function(){
    setTimeout(function() {
        $(".close-button").html('')
   }, 1000);
  })
</script>

app/views/shared/_progressbar.html.erb
<ul id="progressbar">
  <li class= <%= "active" if params[:action] == 'index' %> >
    <%= link_to 'Introduction', root_path, class: 'tooltipped', data: {position: 'bottom', delay: '50', tooltip: 'Introduction'} %>
  </li>
  <li class= <%= "active" if params[:action] == 'validation_helpers' %> >
    <%= link_to 'Validation Helpers', validation_helpers_path, class: 'tooltipped', data: {position: 'bottom', delay: '50', tooltip: 'Validation Helpers'} %>
  </li>
  <li class= <%= "active" if params[:action] == 'common_validation_options' %> >
    <%= link_to 'Common Validation Options', common_validation_options_path, class: 'tooltipped', data: {position: 'bottom', delay: '50', tooltip: 'Common Validation Options'} %>
  </li>
  <li class= <%= "active" if params[:action] == 'strict_validations' %> >
    <%= link_to 'Strict Validations', strict_validations_path, class: 'tooltipped', data: {position: 'bottom', delay: '50', tooltip: 'Strict Validations'} %>
  </li>
  <li class= <%= "active" if params[:action] == 'conditional_validations' %> >
    <%= link_to 'Conditional Validations', conditional_validations_path, class: 'tooltipped', data: {position: 'bottom', delay: '50', tooltip: 'Conditional Validations'} %>
  </li>
  <li class= <%= "active" if params[:action] == 'custom_validations' %> >
    <%= link_to 'Custom Validations', custom_validations_path , class: 'tooltipped', data: {position: 'bottom', delay: '50', tooltip: 'Custom Validations'} %>
  </li>
  <li class= <%= "active" if params[:action] == 'play_with_errors' %> >
    <%= link_to 'Playing with Validation Errors',  play_with_errors_path, class: 'tooltipped', data: {position: 'bottom', delay: '50', tooltip: 'Playing with Validation Errors'} %>
  </li>
</ul>
<script>
$(document).ready(function(){
 $('.tooltipped').tooltip({delay: 50});
});
</script>